{% set name = "libuv" %}
{% set version = "1.10.2" %}
{% set sha256 = "2d740a2adea0f1a19058626f55a076ac41a4ac1f95d4e57cae0c8a634a6cd63b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or not py35]

requirements:
  build:
    - python
    - automake  # [unix]
    - autoconf  # [unix]
    - libtool   # [unix]

test:
  commands:
    - test -f "$PREFIX/include/uv.h"
    - test -f "$PREFIX/lib/libuv.a"  # [unix]
    - test -f "$PREFIX/lib/libuv.la"  # [unix]
    - test -f "$PREFIX/lib/libuv.so.1"  # [linux]
    - test -f "$PREFIX/lib/libuv.1.dylib"  # [osx]
    - test -f "$PREFIX/lib/libuv.so"  # [linux]
    - test -f "$PREFIX/lib/libuv.dylib"  # [osx]

about:
  home: http://libuv.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Cross-platform asynchronous I/O'
  description: |
    libuv is a multi-platform support library with a focus on asynchronous I/O.
    It was primarily developed for use by Node.js, but it’s also used by Luvit,
    Julia, pyuv, and others.
  doc_url: http://docs.libuv.org/
  dev_url: https://github.com/libuv/libuv

extra:
  recipe-maintainers:
    - frol
